;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
  (list "libnotify"
        "dunst"
        "python-virtualenv"
        "python"
        "gcc-toolchain"
        "file"
        "mpd"
        "ibus-rime"
        "ibus"
        "brightnessctl"
        "xhost"
        "python-xlib"
        "rofi"
        "dmenu"
        "mpv"
        "librime"
        "emacs"
        "libvterm"
        "libtool"
        "neovim"
        "curl"
        "zsh"
        "zoxide"
        "feh"
        "syncthing"
        "alacritty"
        "fzf"
        "git-filter-repo"
        "git"
        "nvidia-driver"
        "ncurses"
        "cmake"
        "xclip"
        "emacs-org-roam"
        "clang"
        "xrandr"
        "qutebrowser"
        "picom"
        "polybar"
        "flameshot"
        "xdotool"
        "unzip"
        "eza"
        "node"
        "starship"
        "make"
        "nyxt"
        "bluez"
        "youtube-dl"
        "cuda-toolkit"
        "hugo"
        "bspwm"
        "sxhkd"))
